spring.application.name=bookstore

spring.data.rest.base-path=/api
spring.jpa.show-sql=true

 #spring.profiles.active=h2
 #spring.profiles.active=postgres
spring.profiles.active=rahti

app.user.password=user123
app.admin.password=admin123
