spring.datasource.url=jdbc:postgresql://localhost:5432/k26bookstore
spring.datasource.username=postgres
spring.datasource.password=15032000JkJp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect